### ISSUE TITLE
Version 7.4 can't work on lumen 5.6

### ISSUE THREAD

**Issue by thaibinhindex** [vyuldashev/laravel-queue-rabbitmq#229]
When run php artisan queue:work

```
In RabbitMQQueue.php line 17:
                                                                               
  Declaration of VladimirYuldashev\LaravelQueueRabbitMQ\Queue\RabbitMQQueue::  
  createPayloadArray($job, $queue, $data = '') should be compatible with Illu  
  minate\Queue\Queue::createPayloadArray($job, $data = '')
```

**Comment by hongthach12** [comment]
me too :(,

use Version 7.3 it work :D

**Comment by crypticro** [comment]
got the same issue in Laravel 5.6

**Comment by galexth** [comment]
Laravel 5.6 +

**Comment by vyuldashev** [comment]
Looking into it

**Comment by vyuldashev** [comment]
Fixed in v7.4.2. Sorry about this.

**Comment by adm-bome** [comment]
This hotfix breaks the feature for horizon.

Horizon wants an `id` in the payload. By removing this method `id` is not added to the payload and the events for Horizon will fail when publishing an Job. With the new feature `Horizon` added this method is required.

Laravel changed the signature of `Illuminate\Queue\Queue::createPayload` when moving to 5.7.7

Possible solutions:
- find a workaroud for this. (but not this one)
- as of version 7.4 don't support laravel below version 5.7.7

**For now I would suggest to revert this hotfix.** as soon as posible.
Because people on larvel 5.6 can set a fixed version in composer. And if they want to use the new feature `Horizon` they have to update there whole project.

**Comment by vyuldashev** [comment]
@adm-bome Lets make it a major release.

**Comment by adm-bome** [comment]
> @adm-bome Lets make it a major release.

As i understand correctly: The whole feature horizon (with my added listner) moves up to a major version.

The `Horizon` feature will be removed from 7.* version(s).

**Comment by vyuldashev** [comment]
@adm-bome Right, expect it very soon. I am currently working on it.

**Comment by vyuldashev** [comment]
@adm-bome v8.0.0 released, please test it. Also, v7.5.0 released with removed horizon.

**Comment by adm-bome** [comment]
Tomorrow,  i will check both versions.

**Comment by adm-bome** [comment]
> @adm-bome v8.0.0 released, please test it. Also, v7.5.0 released with removed horizon.
> Tomorrow, i will check both versions.

Nice, everybody happy!!!
Maybe a note in the readme to instruct people to use the `^7.0` tag when not using laravel 5.7 or above.

**Comment by ilyachase** [comment]
> Maybe a note in the readme to instruct people to use the ^7.0 tag when not using laravel 5.7 or above.

It would be very helpful because now I have no idea which version to use with lumen:5.4

**Comment by vyuldashev** [comment]
@ilyachase I agree. I need to introduce version compatibility table.
