### ISSUE TITLE
Queue deamon continue after a RabbitMQ connection lost

### ISSUE THREAD

**Issue by Broutard** [vyuldashev/laravel-queue-rabbitmq#286]
- Laravel Version: 6.6.2
- Package Version: 9.1.2

**Describe the bug**
After a `Lost connection` or a `Connection reset by peer` the job is re-run and the queue deamon continue with a lost rabbitmq connection.

**Steps To Reproduce**
Run a long job (e.g. with a sleep(20)) and restart rabbitmq (or stop networking...) during the job.

**Expected behavior**
The queue deamon must stop.

**Additional context**
In `RabbitMQJob::fire()` method, when a `causedByLostConnection($exception)` occurs, the job is retry after 2sec. 
Caused by this update : https://github.com/vyuldashev/laravel-queue-rabbitmq/commit/edd9cc43082d2846fe517db30aeb29a03b04b04e
It is a `causedByDeadlock()` before this update.

I think, `$this->causedByLostConnection($exception)` should be deleted here.

![image](https://user-images.githubusercontent.com/1552045/70452189-fecd9280-1aa6-11ea-89e5-a8dfb3e58c35.png)

**Comment by Broutard** [comment]
If I remove the `$this->causedByLostConnection($exception)` from `RabbitMQJob::fire()`, it failed with a `Connection reset by peer` and Laravel worker stop the deamon as expected.

**Comment by Broutard** [comment]
If I set `sleep_on_error=false` in the queue config, the worker stops but, my job is processed 3 times (2 times when the RabbitMQ connection is lost... and a 3rd when the worker is restarted).

**Comment by vyuldashev** [comment]
This issue will be fixed in v10

**Comment by vyuldashev** [comment]
Actually, it is already fixed in v10 but it has not been released yet.

**Comment by vyuldashev** [comment]
Actually, it is already fixed in v10 but it has not been released yet.

**Comment by vyuldashev** [comment]
v10 is released. You can try it now.

**Comment by judgej** [comment]
Are we sure this is fixed in in v10? I'm using V10 and finding the same issue. The problem seems to be that the Laravel Worker method (in a trait) the determines whether the connetion has been lost, looks for key phrases in the exception message that is thrown. Those messages are: (a) geared towards *database* connections being dropped (seems like a Laravel bug to me); and (b) do not include any of the phrases that the underlying AMQP library spits out.

Since the AMQP package throws some specific conenctiob lost exceptions, it should be possible to look for those exceptions instead of passing it back to Laravel core to make a best-guess at the exception cause.

I'm using Lumen 6.3.3 so there may be some differences in the way the connection lost detection works.
