### ISSUE TITLE
Laravel 7+ support.

### ISSUE THREAD

**Issue by valehasadli** [vyuldashev/laravel-queue-rabbitmq#337]
Hi @vyuldashev ! Are you planning to support Laravel7+? I think that you have a great job. It would be great for the community.

**Comment by adm-bome** [comment]
There is already support for 7+

**Comment by adm-bome** [comment]
@valehasadli 
For reference and for your concerns [See](https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/332#issuecomment-635287054)

Just try it! 
And I think you can close your issue ;)

**Comment by valehasadli** [comment]
> There is already support for 7+

I'm not sure, cause it needs review. I have tried brand new L7 project, it doesn't work before. Today I'll try again.

**Comment by valehasadli** [comment]
> @valehasadli
> For reference and for your concerns [See](https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/332#issuecomment-635287054)
> 
> Just try it!
> And I think you can close your issue ;)

I just closed, and it would be better transferred to another issue which you are mentioned.

**Comment by adm-bome** [comment]
You didn't have to close the issue, If you have an issue.

I want to know what the issue is realy about.
As I said in the pull-request, i don't have issues in laravel 7. 

The pull-request has changes in it that will break support for laravel/lumen 6.

And thats the main reason this pull-request is not approved yet.

If somebody can point out why? Why does it not wor in laravel 7?
This would be helpfull
