### ISSUE TITLE
horizon cannot auto declare exchange and queue for rabbitmq

### ISSUE THREAD

**Issue by zlpghost** [vyuldashev/laravel-queue-rabbitmq#340]
- Laravel version: 6.18.19
- RabbitMQ version: 3.8.3
- Package version: 10.2.1

**Describe the bug**
After upgrade from vladimir-yuldashev/laravel-queue-rabbitmq 9.0 to 10.2.1
When I run `php artisan horizon`
exchange and queue in rabbitmq cannot auto declare any more.

my config file located at: config/queue.php
'rabbitmq' => [
            'driver' => 'rabbitmq',
            'queue' => env('ABLE_ACTIONS', 'default'),
            'connection' => PhpAmqpLib\Connection\AMQPLazyConnection::class,

            'hosts' => [
                [
                    'host' => env('RABBITMQ_HOST', '127.0.0.1'),
                    'port' => env('RABBITMQ_PORT', 5672),
                    'user' => env('RABBITMQ_USER', 'guest'),
                    'password' => env('RABBITMQ_PASSWORD', 'guest'),
                    'vhost' => env('RABBITMQ_VHOST', '/'),
                ],
            ],

            'options' => [
                'queue' => [
                    'exchange' => env('RABBITMQ_EXCHANGE_NAME', 'cg.topic'),
                    'exchange_type' => env('RABBITMQ_EXCHANGE_TYPE', 'topic'),
                    'exchange_routing_key' => '%s',
                ],

                'ssl_options' => [
                    'ssl_on' => env('RABBITMQ_SSL', false),
                    'cafile' => env('RABBITMQ_SSL_CAFILE', null),
                    'local_cert' => env('RABBITMQ_SSL_LOCALCERT', null),
                    'local_key' => env('RABBITMQ_SSL_LOCALKEY', null),
                    'verify_peer' => env('RABBITMQ_SSL_VERIFY_PEER', true),
                    'passphrase' => env('RABBITMQ_SSL_PASSPHRASE', null),
                ],
            ],

**Steps To Reproduce**
run `php artisan horizon`
check the queue and exchange name config in .env, not able to show in rabbitMq

**Comment by adm-bome** [comment]
This is by design.
This is for the decoupling of app and Message broker.

Horizon or (other) is an manager for one or many workers.
Workers don't define anything.
Workers just look for a queue and if it exists, consumes the messages within the queue.

>Only in very special cases the workers define queues or exchanges and bindings.
But this lib does supports special cases like that. If you run into such cases you most likely have a design flaw.

Publishers can create (direct) queue's when needed. 
When dispatching a job a direct queue is created. When there are no messages there is no need for a (empty) queue.

When working with exchanges you have to manage these from within RabbitMQ (Dashboard/Manager).
When sysadmins manage you rabbitMQ server and define exchanges with queues and bindings you have the option to configure these values in the config.
