### ISSUE TITLE
Queue property of a Job cannot be set

### ISSUE THREAD

**Issue by UmutAkkaya** [vyuldashev/laravel-queue-rabbitmq#349]
Laravel/Lumen version: 7.15.0
RabbitMQ version: 3.8.3
Package version: 10.2.1

**Describe the bug**
I need to queue a job in a separate queue within the worker timeout function. I want to be able to do this by setting the queue to my new one and by releasing the message. Since the queue is protected and doesn't have a setter I cannot do this without using reflection.

**Current behaviour**

- Job times out and hits the timeout function defined within the worker.
- Set queue to a slow running queue -> errors out

**Expected behaviour**
- Job times out and hits the timeout function defined within the worker.
- Set queue to a slow running queue.
- Release the job.

**Comment by adm-bome** [comment]
May i suggest to rethink your workflow.

The timeout feature in a worker or a Job is not something you should use in the flow how a message/Job should be processed or retried.

Timeout purely exists for jobs or worker processes who are running to long on the system. Those "dead" workers consume resources and must be killed when needed. So another worker process can be started by the system or worker managers.

The worker will release the job back to rabbitMQ and when the conditions are met, the worker will mark the job as failed.
When the worker fails the Job the method failed() is called.

This is exacly the place where you should dispatch a new Job to a different queue, for example a slow running queue.

The current Job has failed some how to process, so can be disgarded.

**Comment by UmutAkkaya** [comment]
> 
> 
> May i suggest to rethink your workflow.
> 
> The timeout feature in a worker or a Job is not something you should use in the flow how a message/Job should be processed or retried.
> 
> Timeout purely exists for jobs or worker processes who are running to long on the system. Those "dead" workers consume resources and must be killed when needed. So another worker process can be started by the system or worker managers.
> 
> The worker will release the job back to rabbitMQ and when the conditions are met, the worker will mark the job as failed.
> When the worker fails the Job the method failed() is called.
> 
> This is exacly the place where you should dispatch a new Job to a different queue, for example a slow running queue.
> 
> The current Job has failed some how to process, so can be disgarded.
> 
> See also this [comment](https://github.com/vyuldashev/laravel-queue-rabbitmq/issues/235#issuecomment-623151052)
> 
> When you want to (Not my advice) you can rethink how laravel will handle Jobs and how workers do there work.
> You can write an alternative worker and call extra methods on your Job.

Thanks for the reply! I'm not very familiar with PHP and Rabbitmq so I'm definitely not saying this would be the best approach! I have a couple of questions regarding your solution: Are you referring to the fail method within the worker? If that's the case once the job fails it would be easier to trigger a new one in a separate queue. However, I'm not sure how I would copy this job with all of its data but with a different queue property. When I dump the raw data it has all the properties that I want in the body but I still need to set the queue somehow. Hope that it makes sense

**Comment by adm-bome** [comment]
Somehow.. ;)

I meant the failed() method in the Job itself.
Jobs should be immutable. There is only one way to handle the Job. When the Job has an error or conditions are not met, processing the Job should fail.


Rabbitmq is just a message broker. 
Laravel has Jobs and can store them as messages into a broker. Otherwise known as queue-ing.

Laravel also has workers and they are responsible for retreiving messages from a broker and transform them back to a Job and then processing the data as needed.

So when you dispatch a Job, the worker retreives a message and his messges is resolved through the container and dependicies are constructed. When the Job is resolved/constructed the handle() method on the Job is executed with the parameters and even inject services.

Also read [the manual](https://laravel.com/docs/7.x/queues)
Or  maybe you can use the Failed Event and hook into the failed method.

Im closing the issue because this is not something we have to fix or add to the library ;)

Its a mindset, on how things should work and how to handle them

**Comment by adm-bome** [comment]
Ohw and:

There are 2 types of $job, and this is some what misleading...

1) a broker Job (protected)
2) the actual Laravel Job 

When you want to set properties on the 2th one all you have to do is make public properties and set the properties in the constructor.
 if you want to set properties on a Job
