### ISSUE TITLE
[10.x] Queue worker is getting stopped by timeout when no new jobs available

### ISSUE THREAD

**Issue by codercms** [vyuldashev/laravel-queue-rabbitmq#352]
- Laravel/Lumen version: 6.x
- RabbitMQ version: doesn't matter
- Package version: 10.2.2

**Describe the bug**

When running worker with --timeout argument worker is getting stopped after processing job when no new jobs available.

**Steps To Reproduce**

Just run the queue worker with --timeout argument, for example 10.
Send any job to worker and wait until the job will be processed.
After 10 seconds worker will be terminated by timeout.

**Additional text**
The reason of behavior I wrote above is this line of code:
https://github.com/vyuldashev/laravel-queue-rabbitmq/blob/master/src/Consumer.php#L96

As you can see in that line of code timeout handler is registered, but timeout handler is not cleaned up after the job is processed.
Original Laravel worker does it - https://github.com/illuminate/queue/blob/master/Worker.php#L164

**Comment by codercms** [comment]
@vyuldashev hi! Could you review my PR?

**Comment by adm-bome** [comment]
This also prevents the worker/consumer to stack-up signals.

Because when running multiple jobs/messages the worker is always killed after 10 seconds after the first message was processed.
I could be wrong... i think adding multiple signals is a pile of callbacks when not cleaning this up after the job has been procesed succefully.

**Comment by adm-bome** [comment]
On Oct 9, 2020 14:21, Dmitry <notifications@github.com> wrote:
@vyuldashev hi! Could you review my PR?
