### ISSUE TITLE
How are job failures supposed to be handled?

### ISSUE THREAD

**Issue by judgej** [vyuldashev/laravel-queue-rabbitmq#373]
I am a bit confused about how failed jobs are supposed to be handled, because I am seeing them disappear into a the ether.

I have a job that does little more than throws an exception, and that should fail the job. The lister runs to allow two goes at each job. The job runs, throws an exception, then runs again, and throws another exception. And then that's it, I cannot see any remnant of the job remaining. There is nothing in the `failed_jobs` table, no error messages telling me what the listener is doing with the failed-twice job. Nothing gets routed back to an exchange.

Is that how it is supposed to work? Do I need to hook into the failure events to handle the failed job? Or is this simply broken on my site?

I have tried with `reroute_failed` off (`false`), and tried it on:

```php
            'options' => [
                'queue' => [
                    'reroute_failed' => true,
                    'failed_exchange' => env('RABBITMQ_EXCHANGE_NAME'),
                    'failed_routing_key' => '%s.failed',
```

If I understand correctly, that should send the failed job back to the first exchange it arrived on, with a new routing key. I don't have a route fo that routing key, so it should be picked up by the `alternate-exchange` which is a `fanout` that dumps all unrouted messages into a catch-all queue. It's not in that queue.

How is this supposed to work? Does some routing or options need to be set up on the queues or exchanges to handle failures? Or are these options that get added to the messages when a job is dispatched?

There are many ways to set up and use RabbitMQ, but it is just not clear to me how this package *expects* the queues and exchanges and binding to be set up to do *its thing*. So it is difficult to know if my install is broken, or not configured, or this function is simply not working. Is there any further documentation that describes just what this package does, i.e. what it sends and expects to be set up?

Thanks.

* Lumen 6.3.3
* vladimir-yuldashev/laravel-queue-rabbitmq v10.2.2

**Comment by judgej** [comment]
Let me see if I understand the error routing handling.

For the routing to work, a dead letter route is set up on the queue. This *presumably* means the final failure of a job will `nack` the job, assuming it needs to be rerouted rather than written to the database (which in turn may or may not be working). This can only be done while the queue is being created, so changing the setting means dropping and recreating those queues.

The queues before v10 could be created "on the fly" when first needed at run time. Those queues were created with the settings in the configuration, which included the dead lettering. v10 no longer suports lazy creation (which is the right approach in general IMO) so queues must be set up in advance.

There are now (v10) a bunch of artisan commads to declare the queues, and those commands can be run as a part of the deploy process. Those commands use *different* functions to the older lazy queue declare functionality, and those new functions do NOT set up the dead-lettering, even if in the configuration, so those queues are not set up the same way as they would be for v9.

And that is why I think my failed jobs are disappearing into the ether. Is that an accurate description of how this is working? I like to understand the processes first, before looking at code fixes. My understanding desribed above may be completely wrong. However, I do feel there is a huge chunk of documentation missing on the desired setup and processes that this package implements, and without that documentation, it becomes very hard to diagnose what is going wrong, because it is difficult to get to grips with how it should behave when it is all going *right*.

**Comment by adm-bome** [comment]
## First things first
Hi, I see you are struggling with this library and its core concepts.
This Library is an RabbitMQ Queue Driver for the Laravel Queue Api.

In other words... When working with Laravel and it's Queue Api, this is the bridge between Laravel and how RabbitMQ works under the hood. 
> Build for Laravel Queuing and how Laravel works with queueing ( **The Laravel perspective**).

There are many, many, many,...  use-cases a developer can run into when dealing with queuing.
This library only targets the normal and most common use-cases. How Laravel workers/publishers treat messages and how your Jobs process them is (most likely) **out off scope** of this library.

Of course there are some use-cases, this library has to implement or has to take into account. Only with an exceptional "good written" use-case description and up-votes. We can implement use cases as a new feature. Of course all currently supported use-cases can't break in the process of adding a new feature.

Did you read all documentation about queueing and its basic concepts, laravel queue api, horizon, all available message brokers?

Maybe have a look at this [article](https://laravel-news.com/amqp) and all the documentaion behind it ;) 
> You can think of anik/amqp more as a general package with conveniences on top of php-amqplib, and the RabbitMQ queue driver as a drop-in driver for Laravel queues.

## Laravel Workers
Laravel workers are retrieving the message from a queue. the message can and most likely will instruct Laravel which Job it should create, so it can call the handle method in the Job.

> A Job has two statusses, it either succeed's or it doesn't. There is **no** in between

There are 2 types of failures:
1. When the job generates an exception
2. When the worker determines the Job has processed multiple times but keeps failing, also known as 'max tries'.


The first type of failure is an so called **soft** failure. The Job has an Exception but it is not sure if it can't be processed later. The workers instruct the broker to mark the Job to be processed again (by this worker or an other) or later with a (delay).
> This library takes care of the workflow under the hood how RabbitMQ handles delayed messaqes and also will clean/remove the self created delay queue's. when not needed. (The time is 2 times the delay time, and this is important so messages wont get lost in the process).

The second one is a so called **hard** failure. The Worker determines the Job can't be processed. In a normal flow the worker will throw the message away. (why hold on to something you can't process). Laravel in this case stores the hard failed jobs into the database. This is the default way of how laravel works. 

## Laravel Publisher
This library also gives you an option to instruct the message broker to send the message to an other queue or exchange, when Laravel 'hard' fails the message. 
> The default is pushing the message into the database. This behavior is not altered or touched, so every message should be in the database, if set up correctly.

This setting is called `reroute_failed` and has to be true when u want to use it.
> This extra DLX setting only works when the queue is not yet present in RabbitMQ.

When you push an new Job onto the queue the publisher checks for queue existence and when no queue is present the Publisher is responsible for creating the queue.
> This is only so, when you use direct queuing, which is the default in Laravel. Laravel does not understand the concept of exchanges. 

Laravel by default only uses Direct queuing. Laravel supports multiple message brokers out of the box and RabbitMQ is the only one with exchanges. When Queue's are created by default all queues are bound to the direct exchange. this is how RabbitMQ works.

When working with exchanges you are making advanced queuing concepts possible. Or when you already have advanced queuing in your business and available software you can hook into these advanced concepts / scenario's by configuring extra options.
When you publish against an exchange RabbitMQ will route the messages to a queue (but only if the queue exists and is bound by an routing key)
> When using exchanges, RabbitMQ takes over the routing.

> All the advanced scenario's are not documented because, these are most of the time specific work-flows only applicable to the developers use-cases.


## Notes
Reroute failed messages:
- When the queue is created for the first time. An extra option is set onto the queue. (Also known as `death lettering`). There can be only one DLX setting on a queue and only can be set when creating the queue. 
- Queues can't be recreated or **altered**. You have to destroy the existing queue first, so the queue can be created with it's new settings. A queue and its settings are **immutable**. They can't (or must not) change.

Messages:
- Messages ( when created/pushed with laravel Queue Api),  has an payload with an property set to the Job class.
- Messages (not originating from laravel) have to instruct Laravel, which Job to crate and process.
- Messages are immutable, the must not be altered in the process of adding, retrieving and processing.
- When a message is 'wrong' (wrongly created). The message must be deleted/discarded. Do not alter the messages.

Workers:
- Workers only work a queue. They do **NOT** publish messages or reroute messages other then necessary. (contextual flow)
- Workers check if a queue exists and if it has messages. When the queue does not exist the worker will sleep or be killed depending on its settings. When there is an queue, but there are no messages to process, the same thing will happen.
- Workers should be managed by an Process manager like Horizon or with a system tool as supervisor.
- Workers should run only for a period of time and not as Long running process. PHP is not meant to run for a long period of time, so workers kill themselves when not needed. (A process manager can start a new worker process when needed)

Jobs:
- Jobs know how the message should be handled.
- Jobs are also Immutable, because they are based on an immutable message.
- A Job either fails or it succeeds.

### There is really allot to consider and take into account, when dealing with RabbitMQ and Laravel. I takes a really long time to make your self comfortable with all concepts and the way RabbitMQ works (under the hood) and how Laravel works. And then there are all the use-cases you can think off.

**Comment by adm-bome** [comment]
> v10 no longer suports lazy creation (which is the right approach in general IMO) so queues must be set up in advance.

Yes and No:
When u publish against an queue (directly), an queue get's lazy created with this library. This is because else you loose your message. In fact the amqp-lib will give you an exception because it can not deliver your message ;)

When using exchanges, u leave the routing up to RabbitMQ. When RabbitMQ does not know how to deliver your message to a queue, your message resolves in thin air....
So yes, then you have to declare a queue youself

**Comment by judgej** [comment]
Thank you. That's a great explanation above that should be in the main documentation IMO. Hopefully it will be useful to those using this package in the future even if just on this issue.

**Comment by suyar** [comment]
What is the option `reroute_failed` used for?
I still don't understand.

**Comment by judgej** [comment]
It's a setting used when creating a queue (or as a policy) that sends a message to a specified exchange if it is NACKed, or rejected.

When a job hard fails, this package will NACK the job on the queue; it will tell RabbitMQ that the job failed but there is no need to keep the message any longer because it is not going to try running the job again. Normally RabbitMQ will just discard the message at this point. With the `reroute_failed` option, RabbitMQ will send it to another excange, where you can route it to a queue and handle it how you like from there.

**Comment by adm-bome** [comment]
@judgej 
> but the issue has been closed so I can only assume these options are deprecated now...

Deprecated options? The answer is no. 

>How you deal with the failed job message is out of scope for this package. However...

How to handle failed messages is indeed out of scope of this lib. So is,  explaining every decision ever made or question these decisions. 

It nearly gives, the developer, an extra option. An extra or alternate flow can be created, instead of the default Laravel Database solution.

> The artisan commands to create the same queues in advance...

Stop thinking, that queues and exchanges MUST be created in advance. This is NOT true. Actually you only need to do this as an last resort or if your use-case requires it.

Start thinking decoupled... Your laravel app (publisher), does not care if the message is received (queue/worker), it is only interested in if it was delivered to the mailman (broker). The how, where, who, when, is up-to the mailman.  Its out of the hands of the publisher.

It would be strange that a writer of a book, has to tell the reader of the book, how to publish and sell the book. That is not the Job of the reader nor the writer. Nor should the reader, tell the writer how to write.

The same goes for Companies with employees... As a owner of the company, you don't care how your employees do the're work. But you **trust** your employees to do the Job they are hired for and deliver good results. As an owner you don't specify everything an employee has to do...
Oke, this is maybe too abstract.


>  That is inconsistent...

Those artisan commands are a bonus on-top the **main** functionality this library has to offer. There is simply no-one who has has the need to these extra options in commands. Actually, some options, only became recently available in RabbitMQ.
If its inconsistent or not is a discussion. 

I think its **not** inconsistent because Laravel Queue Api does not make use of these commands, it does not affect anny Laravel flow nor does it care how everything is defined within the broker. These commands a nearly a extra toolset.

Developers can always extend the basic commands. In order to reflect there specific needs. Or create Pull-Requests

**Comment by suyar** [comment]
@adm-bome Thanks for your reply, I seem to understand.

**Comment by suyar** [comment]
@judgej Thanks. This option seems useless to me.

**Comment by adm-bome** [comment]
@suyar The option is useless for almost everyone. Thats because only in advanced cases or special cases it is used. But when u need it its there to use.
