### ISSUE TITLE
Heartbeat issue: "Missed server heartbeat"

### ISSUE THREAD

**Issue by Christophvh** [vyuldashev/laravel-queue-rabbitmq#419]
- Laravel/Lumen version: 7
- RabbitMQ version: 3.8.5
- Package version: 10

Hi, thanks for the work on the package.
I keep getting this error message:

> development.ERROR: Missed server heartbeat {"exception":"[object] (PhpAmqpLib\\Exception\\AMQPHeartbeatMissedException(code: 0): Missed server heartbeat at vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/AbstractIO.php:154)

I tried adding the option 'heartbeat => 15' to the queue array in rabbitMQ config. But the problem still occurs.

**Comment by jvanschie** [comment]
@Christophvh you probably also need to change the heartbeat setting in RabbitMQ on the server.

`See: Otherwise the smaller value of the two is used`

[](https://www.rabbitmq.com/heartbeats.html#heartbeats-timeout)

You also might want to look into the `--max-time` option together with supervisor to restart the PHP process after a specified amount of time. This will avoid issues like timeouts for services like MySQL or Redis, but will also avoid heartbeat issues if the worker run like forever.
https://laravel.com/docs/9.x/queues#processing-jobs-for-a-given-number-of-seconds

**Comment by khepin** [comment]
This issue is being closed due to its age. If you still are encountering the issue, please re-open so we can assist.
