### ISSUE TITLE
assertExtendedOf skips actual implementation of classes itself

### ISSUE THREAD

**Issue by MelchiorKokernoot** [vyuldashev/laravel-queue-rabbitmq#546]
- Laravel/Lumen version: v10.13.0
- RabbitMQ version: 3.9.11
- Package version: v13.3.0

**Describe the bug**
The value `AMQPStreamConnection::class` for the `connection` key of the rabbitmq config in queue.php throws the following error:

```
The connection must extend: AMQPStreamConnection 
```

Only actual subclasses of `AMQPStreamConnection` are valid.

**Steps To Reproduce**

Set `AMQPStreamConnection::class` as the value for the `connection` key in your queue.php rabbitmq config:

```queue.php
'rabbitmq' => [
            ...
            'connection' => AMQPStreamConnection::class,
            ....
```

**Current behavior**

- What happens with the worker?
- Error
- Is the message retried or put back into the queue?
- No
- Is the message acknowledged or rejected?
- No
- Is the message unacked?
- No
- Is the message gone?
- Yes

**Expected behavior**

No error, use the `AMQPStreamConnection::class`

**Additional context**

The problem can be solved by rewriting the `assertExtendedOf` method of the `ConnectionFactory` to be as follows:

```php
protected static function assertExtendedOf($connection, string $abstract): void
    {
        if (! is_a($connection, $abstract, true)) {
            throw new AMQPLogicException(sprintf('The connection must extend: %s', class_basename($abstract)));
        }
    }
```

P.S.
Same would probably go for `assertSSLConnection` as it also uses the assertExtendedOf as well.

**Comment by mindhells** [comment]
same problem here

**Comment by adm-bome** [comment]
May i ask why you want to use the `AMQPStreamConnection::class` directly?

At the moment the  connectionFactory is choosing the right typed class by its given config.

May i suggest (like the readMe says) you extend `AMQPStreamConnection::class`. Your problem should be solved.

**Comment by MelchiorKokernoot** [comment]
Because only 3 months ago, [this was suggested in the readme](https://github.com/vyuldashev/laravel-queue-rabbitmq/blob/3edec270c6fd5e22df42c5f51a0115276f41f579/README.md), so we implemented it like this and since it has always worked, it didn't raise any flags. Until it just now stopped working, and we have found this to be the cause

**Comment by adm-bome** [comment]
You don't need the 'connection' property in config.

If you didn't alter the phplib connection class 'AMQPStreamConnection::class', and i think you didn't.  Remove the 'connection' property from the config. The 'AMQPStreamConnection::class' is most likely the default connection chosen by the factory, and based on your config.

Or extend the 'AMQPStreamConnection::class' if you have your own alterations as a developer.

As a side node and my oppinion:

Peviously the 'connection' property in the config was a bit of a mistery. And the default described by the readme is now depricated. 
98% of all people didn't change this property because the library **didn't support any other class as** the 'LazyConnection::class'. The property was only there to implement your own extension of the 'LazyConnection::class'. 

As if you (as a developer) have special needs you always (in my opinion) have to extend library classes. So you use your own classes. 

> Yes. By introducing the 'new' way of phplib and factory methods, some things changed. More is possible, but this lib is also forcing to extend to classes, if u need it.

Read: **The connection is now realy lazy by defauft.** so if u need the connection to be cached with a open connection, add the 'lazy' property in the config.

**Comment by adm-bome** [comment]
> Of course we can extend the class, but it feels rather weird not being able to explicitly specify which connection class we want to use without having to subclass it.

1. Yes, your right, but previous versions **didn't support** any connection class, other than the 'AMQPLazyConnection::class'. (depricated by the PhpAMQPLib). So a factory was introduced, and the connection property in the config is obsolite and so not needed anymore.

2. This library now uses an factory to choose the right connection class, based on the config. If u want to use your own logic on-top of an 'AMQPStreamConnection::class' or 'AMQPSocketConnection::class' then u can instruct the factory to use your own extended version. **There is no support for your own logic**, but to support the possibility of overwriting, we ensure a developer to extend.

3. The check if a class was extended from 'AMQPLazyConnection::class' was not implemented. probably a mistake or overlooked. So your implementation was posible but was also not supported.

**Comment by adm-bome** [comment]
closed without further explanation
