### ISSUE TITLE
RabbitMQQueue::$currentJob must not be accessed before initialization

### ISSUE THREAD

**Issue by Doclassif** [vyuldashev/laravel-queue-rabbitmq#572]
- Laravel version: 10.2.6
- RabbitMQ version: 3.11.11
- Package version: 13.3.3
- PHP: 8.2.7

Typed property VladimirYuldashev\LaravelQueueRabbitMQ\Queue\RabbitMQQueue::$currentJob must not be accessed before initialization
/opt/apps/laravel/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Queue/RabbitMQQueue.php:580

This error can be resolved by either providing a default value for the property or by initializing the property within the class constructor.

**Comment by Doclassif** [comment]
It's kind of fixed, but it's not =) https://github.com/vyuldashev/laravel-queue-rabbitmq/issues/555

**Comment by iamfarhad** [comment]
you can use this package https://github.com/iamfarhad/LaravelRabbitMQ

**Comment by adm-bome** [comment]
https://github.com/vyuldashev/laravel-queue-rabbitmq/pull/543#pullrequestreview-1456074682

The comment is not entirely true.
Yes: `undefined` and `null` both result in a false value result.

Since PHP 7.4 introduces type-hinting for properties, it is particularly important to provide valid values for all properties, so that all properties have values that match their declared types.

A property that has never been assigned doesn't have a null value, but it is in an undefined state, which will never match any declared type. undefined !== null.

It's **now** best practice to: define properties with a default value or set the property within the construction.
So the `$currentJob` should be defined as `null` value.

All checks for existance, can be shortend by obmitting the is_set() because the `undefined` state, is not possible anymore.
result: Better code and state management, no unexpected results. 

Also see:
[stackoverflow](https://stackoverflow.com/questions/59265625/why-i-am-suddenly-getting-a-typed-property-must-not-be-accessed-before-initiali?newreg=75dc2e81d38144689478151b2629422a)
